language: ruby
rvm:
  - 2.5.1
branches:
  only:
    - master
services:
  - postgresql
  - elasticsearch
before_script:
  - cp config/database.yml.travis config/database.yml
  - cp .env.sample .env
  - RAILS_ENV=test bundle exec rake db:setup
script:
  - bundle exec rubocop
  - bundle exec rspec
