version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: ./bin/rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - database
      - mailcatcher
    stdin_open: true
    tty: true
  database:
    image: postgres:9.6.8
    volumes:
      - .:/app
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: micropop_v2_development
  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - "1080:1080"
      - "1025:1025"
