default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password:
  host: database

development:
  <<: *default
  database: micropop_v2_development

test:
  <<: *default
  database: micropop_v2_test

production:
  <<: *default
  database: micropop_v2_production
  username: micropop_v2
  password:
